Repository AY2021S1-CS2103T-T13-1/tp, pull requests merged in 2020-09, with the labels that each got.

#62 Refactor List Command to take in additional arguments
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Location.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: Implementation, priority.High

#88 Update AboutUs.md to include GitHub usernames
  docs/AboutUs.md
  docs/images/DreamerDragon.png
  docs/images/hhdqirui.jpg
Labels: priority.High

#84 Adapt developer guide to VirusTracker
  docs/DeveloperGuide.md
Labels: Developer Guide, priority.High

#86 Adapt User Guide to VirusTracker
  docs/UserGuide.md
Labels: User Guide, priority.High

#100 Update AboutUs.md with personal details
  docs/AboutUs.md
  docs/images/hopinxian.png
  docs/team/hopinxian.md
Labels: priority.High

#101 Update UserGuide
  docs/UserGuide.md
Labels: User Guide, priority.High

#102 Update developer guide
  docs/DeveloperGuide.md
  docs/team/hopinxian.md
Labels: Developer Guide, priority.High

#93 Adapt ReadMe.md to VirusTracker
  README.md
  docs/_config.yml
  docs/index.md
Labels: priority.High

#105 Fix GitHub pages build failure
  docs/AboutUs.md
  docs/UserGuide.md
Labels: priority.High
