Repository AY2021S1-CS2103T-T13-1/tp, pull requests merged in 2020-11, with the labels that each got.

#269 Implemented Delete visit by index
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteVisitActivityDiagram.puml
  docs/diagrams/DeleteVisitSequenceDiagram.puml
  docs/images/DeleteVisitActivityDiagram.png
  docs/images/DeleteVisitSequenceDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/visit/DeleteVisitCommand.java
  src/main/java/seedu/address/logic/commands/visit/DeleteVisitsCommand.java
  src/main/java/seedu/address/logic/parser/VirusTrackerParser.java
  src/main/java/seedu/address/logic/parser/visit/DeleteVisitCommandParser.java
  src/test/java/seedu/address/logic/commands/visit/DeleteVisitCommandTest.java
  src/test/java/seedu/address/logic/parser/VirusTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/visit/DeleteVisitCommandParserTest.java
Labels: Implementation, documentation, priority.Medium

#271 Improve regex for Email
  docs/UserGuide.md
  src/main/java/seedu/address/model/attribute/Email.java
  src/test/java/seedu/address/model/attribute/EmailTest.java
Labels: Implementation, bug, enhancement, priority.High

#275 Make index error message more user friendly
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug, documentation, priority.Low

#277 Clarify file path in CSV handling methods
  docs/UserGuide.md
Labels: documentation, priority.Low

#280 Add person id and location id to visit panel
  src/main/java/seedu/address/ui/list/VisitCard.java
  src/main/resources/view/VisitListCard.fxml
Labels: Implementation, enhancement, priority.Medium

#272 Add dates to quarantine and infection statuses
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/model/attribute/InfectionStatus.java
  src/main/java/seedu/address/model/attribute/QuarantineStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/AddFromCsvCommandTest/PersonsList.csv
  src/test/data/AddFromCsvCommandTest/PersonsListInvalidPhoneSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListMissingNameFirstRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListWithPreamble.csv
  src/test/data/ExportToCsvCommandTest/TypicalShortenedPersonsList.csv
  src/test/data/JsonPersonBookStorageTest/invalidAndValidPersonPersonBook.json
  src/test/data/JsonPersonBookStorageTest/invalidPersonPersonBook.json
  src/test/data/JsonSerializablePersonBookTest/duplicatePersonPersonBook.json
  src/test/data/JsonSerializablePersonBookTest/typicalPersonsPersonBook.json
  src/test/data/JsonSerializableVisitBookTest/duplicateVisitVisitBook.json
  src/test/data/JsonSerializableVisitBookTest/invalidVisitVisitBook.json
  src/test/data/JsonSerializableVisitBookTest/typicalVisitVisitBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/attribute/InfectionStatusTest.java
  src/test/java/seedu/address/model/attribute/QuarantineStatusTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Implementation, enhancement, priority.High

#276 Remove tags from VirusTracker
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DataGenerator.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/person/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/person/EditPersonCommandParser.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/attribute/InfectionStatus.java
  src/main/java/seedu/address/model/attribute/QuarantineStatus.java
  src/main/java/seedu/address/model/attribute/Tag.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedVisit.java
  src/main/java/seedu/address/ui/list/PersonCard.java
  src/test/data/AddFromCsvCommandTest/PersonsList.csv
  src/test/data/AddFromCsvCommandTest/PersonsListInvalidPhoneSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListMissingNameFirstRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListWithPreamble.csv
  src/test/data/ExportToCsvCommandTest/TypicalShortenedPersonsList.csv
  src/test/data/JsonSerializablePersonBookTest/duplicatePersonPersonBook.json
  src/test/data/JsonSerializablePersonBookTest/typicalPersonsPersonBook.json
  src/test/data/JsonSerializableVisitBookTest/duplicateVisitVisitBook.json
  src/test/data/JsonSerializableVisitBookTest/invalidVisitVisitBook.json
  src/test/data/JsonSerializableVisitBookTest/typicalVisitVisitBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/DataGeneratorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/person/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/EditPersonCommandParserTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/model/attribute/TagTest.java
  src/test/java/seedu/address/model/person/PersonBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVisitTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: Implementation, User Guide, priority.Medium

#273 Refactor list high risk locations to take in argument
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/ModelPredicateTest.java
Labels: Implementation, priority.Medium

#278 Fix generateLocation and generatePeople to only include locations or people from 2 weeks ago.
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/commands/GeneratePeopleCommandTest.java
Labels: Implementation, bug, priority.High

#283 Increase prominence of infection & quarantine statuses
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/model/attribute/InfectionStatus.java
  src/main/java/seedu/address/model/attribute/QuarantineStatus.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/list/LocationCard.java
  src/main/java/seedu/address/ui/list/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/model/attribute/InfectionStatusTest.java
  src/test/java/seedu/address/model/attribute/QuarantineStatusTest.java
Labels: Implementation, enhancement, priority.High

#286 Increase code quality
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/location/AddLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/AddLocationsFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/location/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/EditLocationCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonsFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitsFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/visit/DeleteVisitsCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/commands/GeneratePeopleCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/location/AddLocationsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/location/DeleteLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/location/EditLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/DeleteVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/DeleteVisitsCommandTest.java
Labels: Implementation, bug, priority.High

#281 Make diagrams bigger in the user guide
  docs/UserGuide.md
  docs/images/Ui_Updated.png
  docs/images/ion1.png
  docs/images/ion2.png
Labels: User Guide, documentation, priority.Low

#289 Add page breaks to UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide, bug, documentation, priority.High

#290 Update DG with details done by Wu Qirui
  docs/DeveloperGuide.md
  docs/diagrams/DeleteLocationActivityDiagram.puml
  docs/diagrams/DeleteLocationByIdSequenceDiagram.puml
  docs/diagrams/DeleteLocationByIndexSequenceDiagram.puml
  docs/diagrams/DeleteVisitActivityDiagram.puml
  docs/diagrams/EditLocationActivityDiagram.puml
  docs/diagrams/EditLocationByIdSequenceDiagram.puml
  docs/diagrams/EditLocationByIndexSequenceDiagram.puml
  docs/diagrams/ListHighRiskLocationActivityDiagram.puml
  docs/diagrams/ListHighRiskLocationHaveUserInputSequenceDiagram.puml
  docs/diagrams/ListHighRiskLocationNoUserInputSequenceDiagram.puml
  docs/images/DeleteLocationActivityDiagram.png
  docs/images/DeleteLocationByIdSequenceDiagram.png
  docs/images/DeleteLocationByIndexSequenceDiagram.png
  docs/images/DeleteVisitActivityDiagram.png
  docs/images/EditLocationActivityDiagram.png
  docs/images/EditLocationByIndexSequenceDiagram.png
  docs/images/ListHighRiskLocationActivityDiagram.png
  docs/images/ListHighRiskLocationHaveUserInputSequenceDiagram.png
  docs/images/ListHighRiskLocationNoUserInputSequenceDiagram.png
  docs/images/ListHighRiskLocationSequenceDiagram.png
  docs/images/editLocationByIdSequenceDiagram.png
Labels: Developer Guide

#292 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DisplayListOfAllPeopleActivityDiagram.puml
  docs/images/DisplayListOfAllPeopleActivityDiagram.png
Labels: Developer Guide, User Guide, documentation, priority.Medium

#294 Updated the Design Section in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: Developer Guide

#291 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddFromCsvSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonLocationClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddFromCsvSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeletePersonSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonLocationClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/storage/JsonPersonBookStorage.java
  src/main/java/seedu/address/storage/PersonBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonPersonBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: Developer Guide, User Guide, bug, documentation

#295 Update UG and DG by Pin Xian
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddVisitUniqueIdentifierSequenceDiagram.puml
  docs/diagrams/AddVisitUniqueIdentifiersActivityDiagram.puml
  docs/diagrams/DeletePersonUniqueIdentifierSequenceDiagram.puml
  docs/diagrams/DeletePersonUniqueIdentifiersActivityDiagram.puml
  docs/images/AddVisitUniqueIdentifierSequenceDiagram.png
  docs/images/AddVisitUniqueIdentifiersActivityDiagram.png
  docs/images/EditPersonUniqueIdentifierSequenceDiagram.png
  docs/images/EditPersonUniqueIdentifiersActivityDiagram.png
  docs/images/personPanel.PNG
  docs/images/personPanel.pptx
Labels: Developer Guide, User Guide, priority.High

#299 Update PPP by Siang Ern
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/lowsiangern.md
Labels: documentation, priority.High

#300 PPP by shulong
  docs/AboutUs.md
  docs/team/DreamerDragon.md
Labels: documentation, priority.High

#301 Remove editLocation in DG and PPP draft
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/hhdqirui.md
Labels: Developer Guide, documentation

#303 Fix formatting in UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide, documentation, priority.High

#306 Update Pin Xian PPP
  docs/UserGuide.md
  docs/images/Ui.png
  docs/team/hopinxian.md
Labels: priority.High

#309 Add DG Introductory sections
  docs/DeveloperGuide.md
Labels: Developer Guide, documentation, priority.High

#310 Include assert in generatePeople
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
Labels: Implementation, enhancement, priority.Medium

#311 Update UG according to Jane's comment
  docs/UserGuide.md
Labels: User Guide

#308 PPP draft
  docs/team/kohhanming.md
Labels: documentation, priority.High

#312 changed ppp to lowercase
  docs/AboutUs.md
  docs/team/dreamerdragon.md
Labels: priority.High

#313 Update PPP
  docs/team/kohhanming.md
Labels: documentation, priority.Medium

#317 Fix broken links in DG
  docs/DeveloperGuide.md
  docs/team/kohhanming.md
Labels: Developer Guide, documentation, priority.High

#315 Update UG and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/EditPersonUniqueIdentifierSequenceDiagram.puml
  docs/diagrams/EditPersonUniqueIdentifiersActivityDiagram.puml
  docs/images/EditPersonUniqueIdentifiersActivityDiagram.png
  docs/images/Ui.png
  docs/images/Ui_Updated.png
  docs/images/annotatedUI.png
  docs/images/annotatedUI.pptx
  docs/images/ion1.png
  docs/images/ion2.png
Labels: Developer Guide, User Guide, priority.High

#319 Update spacing
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide

#321 Add apendix effort to toc
  docs/DeveloperGuide.md
Labels: Developer Guide
