Repository AY2021S1-CS2103T-T13-1/tp, pull requests merged in 2020-10, with the labels that each got.

#117 Fix bug with parsing error
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
Labels: Implementation, priority.High

#116 Create InfoHandler class and add functionality to display statistics
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: Implementation, Prerequisite, priority.High

#118 Add unique identifier to Location class
  src/main/java/seedu/address/commons/core/index/exceptions/InvalidIndexException.java
  src/main/java/seedu/address/logic/commands/AddLocationCommand.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/model/location/UniqueLocationList.java
  src/main/java/seedu/address/model/location/exceptions/LocationNotIdentifiableException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedLocation.java
  src/test/data/JsonLocationBookStorageTest/invalidAndValidLocationLocationBook.json
  src/test/data/JsonLocationBookStorageTest/invalidLocationLocationBook.json
  src/test/data/JsonSerializableLocationBookTest/duplicateLocationLocationBook.json
  src/test/data/JsonSerializableLocationBookTest/invalidLocationLocationBook.json
  src/test/data/JsonSerializableLocationBookTest/typicalLocationsLocationBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddLocationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/LocationBookTest.java
  src/test/java/seedu/address/model/location/LocationTest.java
  src/test/java/seedu/address/model/location/UniqueLocationListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLocationTest.java
  src/test/java/seedu/address/testutil/LocationBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalLocations.java
Labels: Implementation, priority.High

#126 Implemented Delete Visits by date and relevant tests
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVisitsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteVisitsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteVisitsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteVisitsCommandParserTest.java
Labels: Implementation, priority.High

#122 Implement delete location functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteLocationCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/location/LocationNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/location/UniqueLocationList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLocationCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteLocationCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/location/LocationNameContainsKeywordsPredicateTest.java
Labels: Implementation, priority.High

#135 Implement edit location functionality
  src/main/java/seedu/address/logic/commands/EditLocationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditLocationCommandParser.java
  src/test/data/JsonSerializableLocationBookTest/typicalLocationsLocationBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/EditLocationDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditLocationCommandParserTest.java
  src/test/java/seedu/address/model/location/UniqueLocationListTest.java
  src/test/java/seedu/address/testutil/EditLocationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/LocationUtil.java
  src/test/java/seedu/address/testutil/TypicalLocations.java
Labels: Implementation, priority.Medium

#132 Implemented generate locations by an infected person
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GenerateLocationsCommandParser.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableVisitBookTest/typicalVisitVisitBook.json
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/parser/GenerateLocationsCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation, priority.Medium

#138 Fix id reference of visits
  src/main/java/seedu/address/logic/commands/AddVisitCommand.java
  src/main/java/seedu/address/logic/parser/AddVisitCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/VisitBuilder.java
  src/test/java/seedu/address/testutil/VisitUtil.java
Labels: Implementation, bug, priority.High

#133 Implement list high risk locations functionality
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListType.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/main/java/seedu/address/model/visit/Visit.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/model/ModelPredicateTest.java
  src/test/java/seedu/address/model/location/LocationTest.java
  src/test/java/seedu/address/testutil/TypicalLocations.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation, priority.Medium

#141 Add functionality for GUI list to match command type
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/location/AddLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/logic/commands/visit/DeleteVisitsCommand.java
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/commands/GeneratePeopleCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/location/DeleteLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/location/EditLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/DeleteVisitsCommandTest.java
Labels: Implementation, bug, priority.High

#146 Implement WrongDateFormatException
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/visit/AddVisitCommandParser.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/visit/AddVisitCommandParserTest.java
Labels: Implementation, priority.High

#153 Refactor parser and fix generate bugs
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/logic/parser/GenerateLocationsCommandParser.java
  src/main/java/seedu/address/logic/parser/GeneratePeopleCommandParser.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/test/java/seedu/address/logic/parser/GenerateLocationsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GeneratePeopleCommandParserTest.java
Labels: Implementation, bug, priority.High

#157 Update UG and DG for v1.2 done by Wu Qirui
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide, documentation, priority.High, type.Case

#156 Update User Guide & Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide, priority.High, type.Case, type.Story

#166 Update UG and DG for V1.2 done by Shulong
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: Developer Guide, User Guide, documentation

#147 Alert user when SHN has been violated
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/test/data/JsonSerializablePersonBookTest/typicalPersonsPersonBook.json
  src/test/data/JsonSerializableVisitBookTest/typicalVisitVisitBook.json
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableVisitBookTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation, priority.High

#170 Implement addFromCsv command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/location/AddLocationsFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonsFromCsvCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitsFromCsvCommand.java
  src/main/java/seedu/address/logic/parser/AddFromCsvCommandParser.java
  src/main/java/seedu/address/logic/parser/DataGenerator.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/VirusTrackerParser.java
  src/test/data/AddFromCsvCommandTest/EmptyCsvFile.csv
  src/test/data/AddFromCsvCommandTest/LocationsList.csv
  src/test/data/AddFromCsvCommandTest/LocationsListInvalidNameSecondRow.csv
  src/test/data/AddFromCsvCommandTest/LocationsListMissingAddressSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsList.csv
  src/test/data/AddFromCsvCommandTest/PersonsListInvalidPhoneSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListMissingNameFirstRow.csv
  src/test/data/AddFromCsvCommandTest/VisitsList.csv
  src/test/data/AddFromCsvCommandTest/VisitsListInvalidDateSecondRow.csv
  src/test/data/AddFromCsvCommandTest/VisitsListMissingDateFirstRow.csv
  src/test/data/JsonSerializableVisitBookTest/typicalVisitVisitBook.json
  src/test/java/seedu/address/logic/commands/location/AddLocationsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitsFromCsvCommandTest.java
  src/test/java/seedu/address/logic/parser/AddFromCsvCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DataGeneratorTest.java
  src/test/java/seedu/address/logic/parser/VirusTrackerParserTest.java
  src/test/java/seedu/address/testutil/TypicalVisitParametersContainers.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation, enhancement, priority.High

#181 Update DG to include details on adding from CSV (Siang Ern)
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddFromCsvActivityDiagram.puml
  docs/diagrams/AddFromCsvSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonLocationClassDiagram.puml
  docs/diagrams/VisitClassDiagram.puml
  docs/images/AddFromCsvActivityDiagram.png
  docs/images/AddFromCsvSequenceDiagram.png
  docs/images/ExamplePersonCsv.png
  docs/images/ModelClassDiagramNew.png
  docs/images/PersonLocationClassDiagram.png
  docs/images/VisitClassDiagram.png
Labels: Developer Guide, documentation, priority.High

#171 Update editLocationCommand to update all visits when the command is executed
  src/main/java/seedu/address/logic/commands/location/EditLocationCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/visit/UniqueVisitList.java
  src/main/java/seedu/address/model/visit/Visit.java
  src/main/java/seedu/address/model/visit/VisitBook.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/location/EditLocationCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/visit/VisitBookTest.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation, priority.Medium

#182 Implement cascade delete for Location
  src/main/java/seedu/address/logic/commands/location/DeleteLocationCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/visit/UniqueVisitList.java
  src/main/java/seedu/address/model/visit/Visit.java
  src/main/java/seedu/address/model/visit/VisitBook.java
  src/test/java/seedu/address/logic/commands/location/DeleteLocationCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/visit/VisitBookTest.java
Labels: Implementation, priority.Medium

#179 Implement cascade delete for Person
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/visit/UniqueVisitList.java
  src/main/java/seedu/address/model/visit/Visit.java
  src/main/java/seedu/address/model/visit/VisitBook.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/visit/VisitBookTest.java
Labels: Implementation, priority.Medium

#185 Update DG with details done by Wu Qirui
  docs/DeveloperGuide.md
  docs/diagrams/ListHighRiskLocationActivityDiagram.puml
  docs/diagrams/ListHighRiskLocationSequenceDiagram.puml
  docs/images/ListHighRiskLocationActivityDiagram.png
  docs/images/ListHighRiskLocationSequenceDiagram.png
Labels: Developer Guide

#184 Make lists automatically sort before displaying
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/logic/commands/location/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/EditLocationCommand.java
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/DeleteVisitsCommand.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/ListComparator.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/main/java/seedu/address/model/attribute/Name.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/location/DeleteLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/location/EditLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/DeleteVisitsCommandTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ModelPredicateTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: Implementation, enhancement, priority.High

#175 Added missing tests for Visit and UniqueVisitList
  src/main/java/seedu/address/model/visit/UniqueVisitList.java
  src/test/java/seedu/address/model/visit/UniqueVisitListTest.java
  src/test/java/seedu/address/model/visit/VisitTest.java
Labels: Implementation

#172 Update editPersonCommand to update all visits when the command is executed
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/visit/UniqueVisitList.java
  src/main/java/seedu/address/model/visit/VisitBook.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
  src/test/java/seedu/address/model/visit/VisitBookTest.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
Labels: Implementation

#189 Update DG and UG (Pin Xian)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddVisitUniqueIdentifierSequenceDiagram.puml
  docs/diagrams/AddVisitUniqueIdentifiersActivityDiagram.puml
  docs/images/AddVisitUniqueIdentifierSequenceDiagram.png
  docs/images/AddVisitUniqueIdentifiersActivityDiagram.png
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
Labels: Developer Guide, User Guide, documentation, priority.High

#192 Added DG and assertions for week 10 tasks for shulong
  docs/DeveloperGuide.md
  docs/diagrams/DeleteVisitsActivityDiagram.puml
  docs/diagrams/DeleteVisitsSequenceDiagram.puml
  docs/images/DeleteVisitsActivityDiagram.png
  docs/images/DeleteVisitsSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
Labels: Developer Guide, priority.High

#196 Use assertion in getNumberOfHighRiskLocations()
  src/main/java/seedu/address/model/InfoHandler.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: Implementation, priority.High

#195 Refactor DataGenerator to require new format
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DataGenerator.java
  src/main/java/seedu/address/logic/parser/person/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/person/EditPersonCommandParser.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/test/data/AddFromCsvCommandTest/LocationsList.csv
  src/test/data/AddFromCsvCommandTest/LocationsListInvalidNameSecondRow.csv
  src/test/data/AddFromCsvCommandTest/LocationsListMissingAddressSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsList.csv
  src/test/data/AddFromCsvCommandTest/PersonsListInvalidPhoneSecondRow.csv
  src/test/data/AddFromCsvCommandTest/PersonsListMissingNameFirstRow.csv
  src/test/data/AddFromCsvCommandTest/VisitsList.csv
  src/test/data/AddFromCsvCommandTest/VisitsListInvalidDateSecondRow.csv
  src/test/data/AddFromCsvCommandTest/VisitsListMissingDateFirstRow.csv
  src/test/data/ExportToCsvCommandTest/TypicalShortenedPersonsList.csv
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/DataGeneratorTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: Implementation, enhancement, priority.High

#201 Update User Guide to include CSV related functionality
  docs/UserGuide.md
  docs/images/ExampleCSVLocations.png
  docs/images/FormatCSV/FormatCsv1.png
  docs/images/FormatCSV/FormatCsv10.png
  docs/images/FormatCSV/FormatCsv2.png
  docs/images/FormatCSV/FormatCsv3.png
  docs/images/FormatCSV/FormatCsv4.png
  docs/images/FormatCSV/FormatCsv5.png
  docs/images/FormatCSV/FormatCsv6.png
  docs/images/FormatCSV/FormatCsv7.png
  docs/images/FormatCSV/FormatCsv8.png
  docs/images/FormatCSV/FormatCsv9.png
Labels: User Guide, documentation, priority.High

#203 Update UG to include using Ids for features
  docs/UserGuide.md
Labels: User Guide, documentation, priority.High

#204 Update UG with details done by Wu Qirui
  docs/UserGuide.md
Labels: User Guide, documentation

#206 Implement an IndexIdPair
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/GenerateLocationsCommand.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/logic/commands/location/AddLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/commands/location/EditLocationCommand.java
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/person/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/logic/parser/GenerateLocationsCommandParser.java
  src/main/java/seedu/address/logic/parser/GeneratePeopleCommandParser.java
  src/main/java/seedu/address/logic/parser/IndexIdPair.java
  src/main/java/seedu/address/logic/parser/ReadOnlyIndexIdPair.java
  src/main/java/seedu/address/logic/parser/location/DeleteLocationCommandParser.java
  src/main/java/seedu/address/logic/parser/location/EditLocationCommandParser.java
  src/main/java/seedu/address/logic/parser/person/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/person/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
  src/test/java/seedu/address/logic/commands/GeneratePeopleCommandTest.java
  src/test/java/seedu/address/logic/commands/location/DeleteLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/location/EditLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/GenerateLocationsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GeneratePeopleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IndexIdPairStub.java
  src/test/java/seedu/address/logic/parser/IndexIdPairTest.java
  src/test/java/seedu/address/logic/parser/VirusTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/location/DeleteLocationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/location/EditLocationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditLocationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: Implementation, priority.High

#209 Update IndexIdPairTest
  src/test/java/seedu/address/logic/parser/IndexIdPairTest.java
Labels: Implementation

#211 Refactor Visit comparator
  src/main/java/seedu/address/model/ListComparator.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/visit/Visit.java
Labels: Implementation, enhancement, priority.High

#214 Code improvement by Shulong
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/visit/AddVisitCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/parser/visit/AddVisitCommandParserTest.java
Labels: bug, priority.High

#218 Fixed UG content mistakes
  docs/UserGuide.md
Labels: User Guide

#217 Fixed high risk locations command bug and list command help message
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ModelPredicate.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: bug, enhancement, priority.High

#212 Fix bugs with misuse of sample visits and update UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/MainApp.java
Labels: Implementation, bug, enhancement, priority.Medium

#220 Increase overall coverage of VirusTracker
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
  src/main/java/seedu/address/logic/parser/IndexIdPair.java
  src/main/java/seedu/address/logic/parser/ListType.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/visit/Visit.java
  src/test/data/AddFromCsvCommandTest/LocationsListWithPreamble.csv
  src/test/data/AddFromCsvCommandTest/PersonsListWithPreamble.csv
  src/test/data/AddFromCsvCommandTest/VisitsListWithPreamble.csv
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExportToCsvCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/location/AddLocationCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/visit/AddVisitCommandTest.java
  src/test/java/seedu/address/logic/parser/DataGeneratorTest.java
  src/test/java/seedu/address/logic/parser/IndexIdPairTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VirusTrackerParserTest.java
  src/test/java/seedu/address/logic/parser/location/DeleteLocationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/visit/AddVisitCommandParserTest.java
  src/test/java/seedu/address/model/InfoHandlerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/attribute/AddressTest.java
  src/test/java/seedu/address/model/attribute/EmailTest.java
  src/test/java/seedu/address/model/attribute/InfectionStatusTest.java
  src/test/java/seedu/address/model/attribute/NameTest.java
  src/test/java/seedu/address/model/attribute/PhoneTest.java
  src/test/java/seedu/address/model/attribute/QuarantineStatusTest.java
  src/test/java/seedu/address/model/attribute/TagTest.java
  src/test/java/seedu/address/model/location/LocationBookTest.java
  src/test/java/seedu/address/model/location/LocationTest.java
  src/test/java/seedu/address/model/location/UniqueLocationListTest.java
  src/test/java/seedu/address/model/person/PersonBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/visit/UniqueVisitListTest.java
  src/test/java/seedu/address/model/visit/VisitBookTest.java
  src/test/java/seedu/address/model/visit/VisitTest.java
  src/test/java/seedu/address/storage/JsonAdaptedVisitTest.java
  src/test/java/seedu/address/storage/JsonLocationBookStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/JsonVisitBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalVisits.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: Implementation, enhancement, priority.Medium

#221 Update user guide
  docs/UserGuide.md
  docs/images/annotatedUI.png
  docs/images/annotatedUI.pptx
  docs/images/helpMessage.png
  docs/images/indexes.png
  docs/images/indexes.pptx
  docs/images/personPanel.PNG
  docs/images/personPanel.pptx
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: User Guide, documentation, priority.Medium

#223 Bug Fixes Before Mock Exam
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/commands/location/EditLocationCommand.java
  src/main/java/seedu/address/logic/commands/person/EditPersonCommand.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditPersonCommandTest.java
  src/test/java/seedu/address/model/ModelStub.java
Labels: Implementation, bug, priority.High

#226 Quick Fix and UG update
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
  src/main/java/seedu/address/model/InfoHandler.java
  src/test/data/ExportToCsvCommandTest/TypicalShortenedPersonsList.csv
Labels: bug, documentation, priority.High

#260 Bug Fix for Mock PE
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/person/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/visit/AddVisitCommand.java
Labels: bug, priority.High
